# app custom Makefile

# Docker repo & image name without version
IMAGE     ?= amir20/dozzle
# Docker image version
IMAGE_VER ?= v4.9.4
# Hostname for external access
APP_SITE  ?= logs.dev.lan
# App names (db/user name etc)
APP_NAME  ?= logs

# ------------------------------------------------------------------------------
# app custom config

# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)


# Unique traefik router name
# Container name prefix
# Value is optional, derived from APP_SITE if empty
APP_TAG=$(APP_TAG)

endef

# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif

# -----------------------------------------------------------------------------
## Custom app targets
#:
